baseurl = "/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Beautiful Hugo"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Hugo Blog Template for GitLab Pages"
  logo = "img/avatar-icon.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Some Person"
  email = "youremail@domain.com"
  facebook = "username"
  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  gitlab = "username"
  github = "username"
  twitter = "username"
  reddit = "username"
  linkedin = "username"
  xing = "username"
  stackoverflow = "users/XXXXXXX/username"
  snapchat = "username"
  instagram = "username"
  youtube = "user/username" # or channel/channelname
  soundcloud = "username"
  spotify = "username"
  bandcamp = "username"
  itchio = "username"
  keybase = "username"

[[menu.main]]
    identifier = "features"
    name = "Features"
    weight = 1

[[menu.main]]
    identifier = "people-management"
    name = "People Management"
    weight = 1
    parent = "features"

[[menu.main]]
    name = "Employee Experience Workflows"
    weight = 1
    parent = "people-management"
    url = "online-hr/people-management/employee-experience"

[[menu.main]]
    name = "Feedback Culture"
    weight = 2
    parent = "people-management"
    url = "online-hr/people-management/continuous-feedback"

[[menu.main]]
    name = "Performance Process & Reviews"
    weight = 3
    parent = "people-management"
    url = "online-hr/people-management/performance"

[[menu.main]]
    name = "Goals"
    weight = 4
    parent = "people-management"
    url = "online-hr/people-management/goals"

[[menu.main]]
    name = "Learning & Development"
    weight = 5
    parent = "people-management"
    url = "online-hr/analytics/learning-development"

[[menu.main]]
    name = "Leadership Tools"
    weight = 6
    parent = "people-management"
    url = "online-hr/analytics/leadership-discipline"

[[menu.main]]
    identifier = "company"
    name = "Company"
    weight = 2

[[menu.main]]
    identifier = "about-intellihr"
    name = "About intelliHR"
    weight = 1
    parent = "company"

[[menu.main]]
    name = "Our Story"
    weight = 1
    url = "company/our-story"
    parent = "about-intellihr"

[[menu.main]]
    name = "Our People"
    weight = 2
    url = "company/our-people"
    parent = "about-intellihr"

[[menu.main]]
    name = "Pricing"
    weight = 3
    url = "pricing"

[[menu.main]]
    identifier = "partners"
    name = "Partners"
    weight = 4

[[menu.main]]
    identifier = "resources"
    name = "Resources"
    weight = 5

[[menu.main]]
    name = "Blog"
    weight = 6
    url = "insights"
